service:
  name: lambdda-layer-demo

plugins:
  - serverless-webpack
  - serverless-layers

custom:
  serverless-layers:
    layersDeploymentBucket: lambda-layers-deploy-demo

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1

functions:
  index:
    handler: index.handler
    events:
      - http:
          method: get
          path: hello
